detection:
  face:
    detection_interval: 5    # frames
    min_confidence: 0.8
  eye_tracking:
    gaze_threshold: 2          # seconds
    blink_threshold: 0.3       # EAR threshold for blink detection
    gaze_sensitivity: 15       # pixels threshold for gaze detection
    consecutive_frames: 2      # frames for gaze change detection
  multi_face:
    alert_threshold: 3      # frames
  objects:
    min_confidence: 0.65  # Detection confidence threshold
    detection_interval: 5 # frames between detections
    max_fps: 5          # Maximum detection frames per second
  audio_monitoring:
    enabled: true
    sample_rate: 16000
    chunk_size: 4096
    # energy_threshold: 0.001
    # zcr_threshold: 0.35
    whisper_enabled: true  # Enable only when needed
    whisper_model: "medium"
    input_device_index: 2
        
logging:
  log_path: "./session_data/logs"
  alert_cooldown: 10          # seconds



global:
  output_path: "./reports"

                   # Seconds to wait before attempting to pin
reporting:
  image_dir: "./reports/generated/images"  # New subdirectory for images
  output_dir: "./reports/generated"
  wkhtmltopdf_path: "C:\\Users\\manas\\OneDrive\\Desktop\\Chatbot Assistant\\interview_chatbot_assistant\\src\\report_generation\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"
  rating_thresholds:
    TOTAL VIOLATIONS:
       critical: 7
       major: 5
       medium: 3
    FACE_DISAPPEARED:
       critical: 7
       major: 5
       medium: 3
    FORBIDDEN_OBJECT:
       critical: 3
       major: 2
       medium: 1
    MULTIPLE_FACES:
       critical: 3
       major: 2
       medium: 1   
    EYE_MOVEMENT:
       critical: 5
       major: 4
       medium: 3



  severity_levels:
    FACE_DISAPPEARED: 1
    GAZE_AWAY: 2
    MULTIPLE_FACES: 4
    OBJECT_DETECTED: 5
    AUDIO_DETECTED: 3
  # config/config.yaml
recording:
  poll_total_secs: 180       # total time to wait for cloud recording (seconds)
  poll_interval_secs: 6      # interval between polls (seconds)
